# Generated by Django 5.1 on 2024-08-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45, unique=True)),
                ('color', models.CharField(max_length=6)),
                ('tamanio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
