# Generated by Django 5.1 on 2024-08-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('contacto_duenio', models.CharField(max_length=45)),
                ('especie', models.CharField(max_length=45)),
            ],
        ),
    ]
